import 'package:flutter/material.dart';

// Review class to store comment, stars, and reviewer name
class Review {
  final String comment;
  final int stars;
  final String reviewerName;

  Review({
    required this.comment,
    required this.stars,
    required this.reviewerName,
  });
}

class Doctor {
  final String name;
  final String specialty;
  final double rating;
  final int numberOfReviews;
  final String trait;
  final String location;
  final double fees;
  final int waitingTimeMinutes;
  final String availability;
  final bool isSponsored;
  final String imageUrl;
  final String? bio;
  final List<Review>? reviews;

  Doctor({
    required this.name,
    required this.specialty,
    required this.rating,
    required this.numberOfReviews,
    required this.trait,
    required this.location,
    required this.fees,
    required this.waitingTimeMinutes,
    required this.availability,
    this.isSponsored = false,
    required this.imageUrl,
    this.bio,
    this.reviews,
  });
}

class DoctorsData extends StatelessWidget {
  static final List<Doctor> doctors = [
    Doctor(
      name: 'Dr. Ahmed Khaled',
      specialty: 'Cardiology',
      rating: 4.8,
      numberOfReviews: 980,
      trait: 'Patient',
      location: 'Cairo: Nasr City',
      fees: 200.0,
      waitingTimeMinutes: 30,
      availability: 'Sun, 27 Apr 02:00 PM',
      isSponsored: false,
      imageUrl: 'https://example.com/images/doctor_ahmed_khaled.jpg',
      bio: 'Dr. Ahmed Khaled specializes in cardiovascular health, with expertise in managing heart conditions and preventive care over 12 years.',
      reviews: [
        Review(comment: 'Very caring and thorough, explained everything clearly.', stars: 5, reviewerName: 'Mohamed Ali'),
        Review(comment: 'Good experience, but waiting time was a bit long.', stars: 4, reviewerName: 'Fatima Hassan'),
        Review(comment: 'Highly professional, helped with my heart condition.', stars: 5, reviewerName: 'Sara Ahmed'),
        Review(comment: 'Friendly and knowledgeable, highly recommend.', stars: 5, reviewerName: 'Khaled Mostafa'),
        Review(comment: 'Great doctor, but appointment scheduling needs improvement.', stars: 4, reviewerName: 'Nour El Din'),
      ],
    ),
    Doctor(
      name: 'Dr. Fatima Mostafa',
      specialty: 'Cardiology',
      rating: 4.9,
      numberOfReviews: 1200,
      trait: 'Experienced',
      location: 'Alexandria: Smouha',
      fees: 250.0,
      waitingTimeMinutes: 45,
      availability: 'Mon, 28 Apr 03:00 PM',
      isSponsored: true,
      imageUrl: 'https://example.com/images/doctor_fatima_mostafa.jpg',
      bio: 'With 15 years in cardiology, Dr. Fatima excels in treating complex heart diseases, focusing on personalized care and patient education.',
      reviews: [
        Review(comment: 'Amazing doctor, very attentive and professional.', stars: 5, reviewerName: 'Aya Mahmoud'),
        Review(comment: 'Explained my condition in detail, highly recommend.', stars: 5, reviewerName: 'Omar Hassan'),
        Review(comment: 'Good care, but clinic was a bit crowded.', stars: 4, reviewerName: 'Laila Ibrahim'),
        Review(comment: 'Very knowledgeable, made me feel at ease.', stars: 5, reviewerName: 'Youssef Hamed'),
        Review(comment: 'Professional service, but fees are high.', stars: 4, reviewerName: 'Rana Ahmed'),
      ],
    ),
    Doctor(
      name: 'Dr. Omar Hassan',
      specialty: 'Cardiology',
      rating: 4.7,
      numberOfReviews: 850,
      trait: 'Good Listener',
      location: 'Giza: Dokki',
      fees: 180.0,
      waitingTimeMinutes: 40,
      availability: 'Tue, 29 Apr 01:00 PM',
      isSponsored: false,
      imageUrl: 'https://example.com/images/doctor_omar_hassan.jpg',
      bio: 'Dr. Omar Hassan is a compassionate cardiologist specializing in heart failure management and non-invasive diagnostics, ensuring empathetic care.',
      reviews: [
        Review(comment: 'Very understanding, great experience.', stars: 5, reviewerName: 'Mona Salah'),
        Review(comment: 'Helpful, but appointment took time.', stars: 4, reviewerName: 'Ali Hamed'),
        Review(comment: 'Excellent doctor, highly skilled.', stars: 5, reviewerName: 'Nourhan Mohamed'),
        Review(comment: 'Friendly and thorough, recommended.', stars: 5, reviewerName: 'Khaled Mostafa'),
        Review(comment: 'Good service, but parking was an issue.', stars: 4, reviewerName: 'Amal Fathy'),
      ],
    ),
    Doctor(
      name: 'Dr. Nour El Din',
      specialty: 'Cardiology',
      rating: 4.6,
      numberOfReviews: 700,
      trait: 'Friendly',
      location: 'Mansoura: El Gomhoria St.',
      fees: 220.0,
      waitingTimeMinutes: 35,
      availability: 'Wed, 30 Apr 04:00 PM',
      isSponsored: false,
      imageUrl: 'https://example.com/images/doctor_nour_eldin.jpg',
      bio: 'Dr. Nour El Din offers expert cardiology care, specializing in arrhythmia treatment and cardiac rehabilitation with a warm demeanor.',
      reviews: [
        Review(comment: 'Very friendly and professional.', stars: 5, reviewerName: 'Hala Gamal'),
        Review(comment: 'Good doctor, but clinic needs better organization.', stars: 4, reviewerName: 'Amr Mostafa'),
        Review(comment: 'Helped me a lot with my condition.', stars: 5, reviewerName: 'Rana Ahmed'),
        Review(comment: 'Knowledgeable and approachable.', stars: 5, reviewerName: 'Sherif Mahmoud'),
        Review(comment: 'Slightly delayed, but great care.', stars: 4, reviewerName: 'Tarek Abdel Aziz'),
      ],
    ),
    Doctor(
      name: 'Dr. Sara Abdel Rahman',
      specialty: 'Cardiology',
      rating: 4.9,
      numberOfReviews: 1100,
      trait: 'Professional',
      location: 'Cairo: Maadi',
      fees: 230.0,
      waitingTimeMinutes: 50,
      availability: 'Thu, 01 May 02:00 PM',
      isSponsored: true,
      imageUrl: 'https://example.com/images/doctor_sara_abdelrahman.jpg',
      bio: 'Dr. Sara is a dedicated cardiologist with a focus on interventional cardiology and patient wellness, with over 10 years of experience.',
      reviews: [
        Review(comment: 'Extremely professional and caring.', stars: 5, reviewerName: 'Mona Salah'),
        Review(comment: 'Great experience, highly recommend.', stars: 5, reviewerName: 'Ali Hamed'),
        Review(comment: 'Good care, but long wait time.', stars: 4, reviewerName: 'Nourhan Mohamed'),
        Review(comment: 'Very thorough and knowledgeable.', stars: 5, reviewerName: 'Khaled Mostafa'),
        Review(comment: 'Professional, but clinic was crowded.', stars: 4, reviewerName: 'Amal Fathy'),
      ],
    ),
    Doctor(
      name: 'Dr. Mohamed Ali',
      specialty: 'Dentistry',
      rating: 4.5,
      numberOfReviews: 600,
      trait: 'Gentle',
      location: 'Cairo: Heliopolis',
      fees: 150.0,
      waitingTimeMinutes: 20,
      availability: 'Sat, 26 Apr 10:00 AM',
      isSponsored: false,
      imageUrl: 'https://example.com/images/doctor_mohamed_ali.jpg',
      bio: 'Dr. Mohamed Ali is a skilled dentist specializing in cosmetic dentistry and oral health, known for his gentle and caring approach.',
      reviews: [
        Review(comment: 'Gentle and professional, great dentist.', stars: 5, reviewerName: 'Hala Gamal'),
        Review(comment: 'Good service, but booking was tricky.', stars: 4, reviewerName: 'Amr Mostafa'),
        Review(comment: 'Very skilled, my teeth look great.', stars: 5, reviewerName: 'Rana Ahmed'),
        Review(comment: 'Friendly and made me feel comfortable.', stars: 5, reviewerName: 'Sherif Mahmoud'),
        Review(comment: 'Average experience, clinic needs improvement.', stars: 3, reviewerName: 'Tarek Abdel Aziz'),
      ],
    ),
    Doctor(
      name: 'Dr. Aya Mahmoud',
      specialty: 'Dentistry',
      rating: 4.7,
      numberOfReviews: 750,
      trait: 'Skilled',
      location: 'Alexandria: Miami',
      fees: 180.0,
      waitingTimeMinutes: 25,
      availability: 'Sun, 27 Apr 11:00 AM',
      isSponsored: true,
      imageUrl: 'https://example.com/images/doctor_aya_mahmoud.jpg',
      bio: 'Dr. Aya Mahmoud excels in restorative dentistry, providing high-quality care with a focus on patient comfort and satisfaction.',
      reviews: [
        Review(comment: 'Very skilled, amazing results.', stars: 5, reviewerName: 'Mona Salah'),
        Review(comment: 'Good dentist, but slightly expensive.', stars: 4, reviewerName: 'Ali Hamed'),
        Review(comment: 'Professional and friendly service.', stars: 5, reviewerName: 'Nourhan Mohamed'),
        Review(comment: 'Great care, highly recommend.', stars: 5, reviewerName: 'Khaled Mostafa'),
        Review(comment: 'Clinic was busy, but good treatment.', stars: 4, reviewerName: 'Amal Fathy'),
      ],
    ),
    Doctor(
      name: 'Dr. Khaled Samir',
      specialty: 'Dentistry',
      rating: 4.6,
      numberOfReviews: 680,
      trait: 'Patient',
      location: 'Giza: Mohandessin',
      fees: 160.0,
      waitingTimeMinutes: 30,
      availability: 'Mon, 28 Apr 09:00 AM',
      isSponsored: false,
      imageUrl: 'https://example.com/images/doctor_khaled_samir.jpg',
      bio: 'Dr. Khaled Samir is a patient-focused dentist with expertise in orthodontics and preventive dental care, ensuring a comfortable experience.',
      reviews: [
        Review(comment: 'Patient and professional, great dentist.', stars: 5, reviewerName: 'Hala Gamal'),
        Review(comment: 'Good care, but waiting time was long.', stars: 4, reviewerName: 'Amr Mostafa'),
        Review(comment: 'Very skilled, fixed my braces perfectly.', stars: 5, reviewerName: 'Rana Ahmed'),
        Review(comment: 'Friendly and thorough.', stars: 5, reviewerName: 'Sherif Mahmoud'),
        Review(comment: 'Average service, clinic needs better staff.', stars: 3, reviewerName: 'Tarek Abdel Aziz'),
      ],
    ),
    Doctor(
      name: 'Dr. Laila Ibrahim',
      specialty: 'Dentistry',
      rating: 4.8,
      numberOfReviews: 900,
      trait: 'Friendly',
      location: 'Tanta: El Geish St.',
      fees: 170.0,
      waitingTimeMinutes: 15,
      availability: 'Tue, 29 Apr 12:00 PM',
      isSponsored: false,
      imageUrl: 'https://example.com/images/doctor_laila_ibrahim.jpg',
      bio: 'Dr. Laila Ibrahim specializes in pediatric dentistry, creating a friendly environment for patients with her warm and professional approach.',
      reviews: [
        Review(comment: 'Amazing with kids, very friendly.', stars: 5, reviewerName: 'Mona Salah'),
        Review(comment: 'Good dentist, but clinic was crowded.', stars: 4, reviewerName: 'Ali Hamed'),
        Review(comment: 'Professional and caring, highly recommend.', stars: 5, reviewerName: 'Nourhan Mohamed'),
        Review(comment: 'Great experience for my child.', stars: 5, reviewerName: 'Khaled Mostafa'),
        Review(comment: 'Slightly delayed, but excellent care.', stars: 4, reviewerName: 'Amal Fathy'),
      ],
    ),
    Doctor(
      name: 'Dr. Youssef Hamed',
      specialty: 'Dentistry',
      rating: 4.9,
      numberOfReviews: 1000,
      trait: 'Professional',
      location: 'Cairo: Zamalek',
      fees: 200.0,
      waitingTimeMinutes: 20,
      availability: 'Wed, 30 Apr 01:00 PM',
      isSponsored: true,
      imageUrl: 'https://example.com/images/doctor_youssef_hamed.jpg',
      bio: 'Dr. Youssef Hamed is a leading dentist in implantology and cosmetic procedures, delivering exceptional results with professionalism.',
      reviews: [
        Review(comment: 'Professional and skilled, amazing implants.', stars: 5, reviewerName: 'Hala Gamal'),
        Review(comment: 'Good service, but expensive.', stars: 4, reviewerName: 'Amr Mostafa'),
        Review(comment: 'Very thorough, highly recommend.', stars: 5, reviewerName: 'Rana Ahmed'),
        Review(comment: 'Excellent dentist, great results.', stars: 5, reviewerName: 'Sherif Mahmoud'),
        Review(comment: 'Clinic needs better organization.', stars: 4, reviewerName: 'Tarek Abdel Aziz'),
      ],
    ),
    Doctor(
      name: 'Dr. Mayada Alashry',
      specialty: 'Dermatology',
      rating: 5.0,
      numberOfReviews: 1520,
      trait: 'Good Listener',
      location: 'Tanta: Elbahr St.',
      fees: 160.0,
      waitingTimeMinutes: 51,
      availability: 'Sat, 26 Apr 01:00 PM',
      isSponsored: true,
      imageUrl: 'https://example.com/images/doctor_mayada_alashry.jpg',
      bio: 'Dr. Mayada Alashry is a dermatologist specializing in skin rejuvenation and allergy treatment, known for her attentive and caring approach.',
      reviews: [
        Review(comment: 'Very attentive, cleared my skin issues.', stars: 5, reviewerName: 'Mona Salah'),
        Review(comment: 'Good care, but long wait time.', stars: 4, reviewerName: 'Ali Hamed'),
        Review(comment: 'Professional and knowledgeable.', stars: 5, reviewerName: 'Nourhan Mohamed'),
        Review(comment: 'Amazing results, highly recommend.', stars: 5, reviewerName: 'Khaled Mostafa'),
        Review(comment: 'Clinic was busy, but great service.', stars: 4, reviewerName: 'Amal Fathy'),
      ],
    ),
    Doctor(
      name: 'Dr. Hala Gamal',
      specialty: 'Dermatology',
      rating: 4.8,
      numberOfReviews: 1100,
      trait: 'Skilled',
      location: 'Cairo: Downtown',
      fees: 180.0,
      waitingTimeMinutes: 40,
      availability: 'Sun, 27 Apr 02:00 PM',
      isSponsored: false,
      imageUrl: 'https://example.com/images/doctor_hala_gamal.jpg',
      bio: 'Dr. Hala Gamal offers advanced dermatological care, focusing on acne treatment and cosmetic dermatology with a patient-first mindset.',
      reviews: [
        Review(comment: 'Skilled and professional, great results.', stars: 5, reviewerName: 'Hala Gamal'),
        Review(comment: 'Good treatment, but clinic needs improvement.', stars: 4, reviewerName: 'Amr Mostafa'),
        Review(comment: 'Helped with my acne, highly recommend.', stars: 5, reviewerName: 'Rana Ahmed'),
        Review(comment: 'Friendly and thorough.', stars: 5, reviewerName: 'Sherif Mahmoud'),
        Review(comment: 'Average experience, long wait.', stars: 3, reviewerName: 'Tarek Abdel Aziz'),
      ],

    ),
    Doctor(
      name: 'Dr. Amr Mostafa',
      specialty: 'Dermatology',
      rating: 4.7,
      numberOfReviews: 950,
      trait: 'Experienced',
      location: 'Alexandria: Sidi Gaber',
      fees: 190.0,
      waitingTimeMinutes: 45,
      availability: 'Mon, 28 Apr 03:00 PM',
      isSponsored: false,
      imageUrl: 'https://example.com/images/doctor_amr_mostafa.jpg',
      bio: 'With 14 years of experience, Dr. Amr Mostafa specializes in psoriasis and skin cancer screening, providing thorough and expert care.',
      reviews: [
        Review(comment: 'Very experienced, great care.', stars: 5, reviewerName: 'Mona Salah'),
        Review(comment: 'Good doctor, but appointment was delayed.', stars: 4, reviewerName: 'Ali Hamed'),
        Review(comment: 'Professional and thorough.', stars: 5, reviewerName: 'Nourhan Mohamed'),
        Review(comment: 'Helped with my skin condition.', stars: 5, reviewerName: 'Khaled Mostafa'),
        Review(comment: 'Clinic needs better scheduling.', stars: 4, reviewerName: 'Amal Fathy'),
      ],
    ),
    Doctor(
      name: 'Dr. Rana Ahmed',
      specialty: 'Dermatology',
      rating: 4.9,
      numberOfReviews: 1300,
      trait: 'Friendly',
      location: 'Giza: Haram',
      fees: 170.0,
      waitingTimeMinutes: 35,
      availability: 'Tue, 29 Apr 04:00 PM',
      isSponsored: true,
      imageUrl: 'https://example.com/images/doctor_rana_ahmed.jpg',
      bio: 'Dr. Rana Ahmed is a friendly dermatologist with expertise in laser treatments and skin care, ensuring a welcoming patient experience.',
      reviews: [
        Review(comment: 'Friendly and skilled, amazing results.', stars: 5, reviewerName: 'Hala Gamal'),
        Review(comment: 'Good care, but slightly expensive.', stars: 4, reviewerName: 'Amr Mostafa'),
        Review(comment: 'Very professional, great laser treatment.', stars: 5, reviewerName: 'Rana Ahmed'),
        Review(comment: 'Welcoming and thorough.', stars: 5, reviewerName: 'Sherif Mahmoud'),
        Review(comment: 'Clinic was crowded, but good service.', stars: 4, reviewerName: 'Tarek Abdel Aziz'),
      ],
    ),
    Doctor(
      name: 'Dr. Sherif Mahmoud',
      specialty: 'Dermatology',
      rating: 4.6,
      numberOfReviews: 800,
      trait: 'Professional',
      location: 'Mansoura: El Gomhoria St.',
      fees: 200.0,
      waitingTimeMinutes: 50,
      availability: 'Wed, 30 Apr 01:00 PM',
      isSponsored: false,
      imageUrl: 'https://example.com/images/doctor_sherif_mahmoud.jpg',
      bio: 'Dr. Sherif Mahmoud provides professional dermatological care, specializing in chronic skin conditions and aesthetic treatments.',
      reviews: [
        Review(comment: 'Professional and knowledgeable.', stars: 5, reviewerName: 'Mona Salah'),
        Review(comment: 'Good treatment, but long wait.', stars: 4, reviewerName: 'Ali Hamed'),
        Review(comment: 'Helped with my skin condition.', stars: 5, reviewerName: 'Nourhan Mohamed'),
        Review(comment: 'Great care, highly recommend.', stars: 5, reviewerName: 'Khaled Mostafa'),
        Review(comment: 'Average experience, clinic needs improvement.', stars: 3, reviewerName: 'Amal Fathy'),
      ],
    ),
    Doctor(
      name: 'Dr. Tarek Abdel Aziz',
      specialty: 'Ear (ENT)',
      rating: 4.7,
      numberOfReviews: 850,
      trait: 'Patient',
      location: 'Cairo: Shubra',
      fees: 150.0,
      waitingTimeMinutes: 30,
      availability: 'Sat, 26 Apr 03:00 PM',
      isSponsored: false,
      imageUrl: 'https://example.com/images/doctor_tarek_abdelaziz.jpg',
      bio: 'Dr. Tarek Abdel Aziz is an ENT specialist with a focus on sinus disorders and hearing loss, known for his patient-centered care.',
      reviews: [
        Review(comment: 'Very patient and thorough.', stars: 5, reviewerName: 'Hala Gamal'),
        Review(comment: 'Good care, but clinic was busy.', stars: 4, reviewerName: 'Amr Mostafa'),
        Review(comment: 'Helped with my sinus issues.', stars: 5, reviewerName: 'Rana Ahmed'),
        Review(comment: 'Friendly and professional.', stars: 5, reviewerName: 'Sherif Mahmoud'),
        Review(comment: 'Slightly delayed, but good service.', stars: 4, reviewerName: 'Tarek Abdel Aziz'),
      ],
    ),
    Doctor(
      name: 'Dr. Mona Salah',
      specialty: 'Ear (ENT)',
      rating: 4.8,
      numberOfReviews: 1000,
      trait: 'Skilled',
      location: 'Alexandria: Cleopatra',
      fees: 160.0,
      waitingTimeMinutes: 25,
      availability: 'Sun, 27 Apr 04:00 PM',
      isSponsored: true,
      imageUrl: 'https://example.com/images/doctor_mona_salah.jpg',
      bio: 'Dr. Mona Salah excels in treating throat and ear conditions, offering skilled and compassionate care with advanced diagnostic techniques.',
      reviews: [
        Review(comment: 'Skilled and caring, great experience.', stars: 5, reviewerName: 'Mona Salah'),
        Review(comment: 'Good doctor, but appointment was delayed.', stars: 4, reviewerName: 'Ali Hamed'),
        Review(comment: 'Very professional, helped a lot.', stars: 5, reviewerName: 'Nourhan Mohamed'),
        Review(comment: 'Highly recommend, excellent care.', stars: 5, reviewerName: 'Khaled Mostafa'),
        Review(comment: 'Clinic needs better organization.', stars: 4, reviewerName: 'Amal Fathy'),
      ],
    ),
    Doctor(
      name: 'Dr. Ali Hamed',
      specialty: 'Ear (ENT)',
      rating: 4.6,
      numberOfReviews: 700,
      trait: 'Friendly',
      location: 'Giza: Faisal',
      fees: 140.0,
      waitingTimeMinutes: 20,
      availability: 'Mon, 28 Apr 02:00 PM',
      isSponsored: false,
      imageUrl: 'https://example.com/images/doctor_ali_hamed.jpg',
      bio: 'Dr. Ali Hamed is a friendly ENT specialist specializing in pediatric ENT issues, creating a comfortable environment for patients.',
      reviews: [
        Review(comment: 'Very friendly, great with kids.', stars: 5, reviewerName: 'Hala Gamal'),
        Review(comment: 'Good care, but clinic was small.', stars: 4, reviewerName: 'Amr Mostafa'),
        Review(comment: 'Professional and thorough.', stars: 5, reviewerName: 'Rana Ahmed'),
        Review(comment: 'Helped my child a lot.', stars: 5, reviewerName: 'Sherif Mahmoud'),
        Review(comment: 'Average experience, long wait.', stars: 3, reviewerName: 'Tarek Abdel Aziz'),
      ],
    ),
    Doctor(
      name: 'Dr. Nourhan Mohamed',
      specialty: 'Ear (ENT)',
      rating: 4.9,
      numberOfReviews: 1200,
      trait: 'Professional',
      location: 'Tanta: El Nady St.',
      fees: 170.0,
      waitingTimeMinutes: 35,
      availability: 'Tue, 29 Apr 01:00 PM',
      isSponsored: true,
      imageUrl: 'https://example.com/images/doctor_nourhan_mohamed.jpg',
      bio: 'Dr. Nourhan Mohamed provides professional ENT care, with expertise in minimally invasive sinus surgeries and patient wellness.',
      reviews: [
        Review(comment: 'Professional and skilled, great care.', stars: 5, reviewerName: 'Mona Salah'),
        Review(comment: 'Good service, but slightly expensive.', stars: 4, reviewerName: 'Ali Hamed'),
        Review(comment: 'Very thorough, highly recommend.', stars: 5, reviewerName: 'Nourhan Mohamed'),
        Review(comment: 'Excellent doctor, great results.', stars: 5, reviewerName: 'Khaled Mostafa'),
        Review(comment: 'Clinic was crowded, but good care.', stars: 4, reviewerName: 'Amal Fathy'),
      ],
    ),
    Doctor(
      name: 'Dr. Khaled Mostafa',
      specialty: 'Ear (ENT)',
      rating: 4.5,
      numberOfReviews: 650,
      trait: 'Experienced',
      location: 'Cairo: Heliopolis',
      fees: 180.0,
      waitingTimeMinutes: 40,
      availability: 'Wed, 30 Apr 03:00 PM',
      isSponsored: false,
      imageUrl: 'https://example.com/images/doctor_khaled_mostafa.jpg',
      bio: 'With over 10 years in ENT, Dr. Khaled Mostafa specializes in voice disorders and advanced diagnostic procedures.',
      reviews: [
        Review(comment: 'Experienced and professional.', stars: 5, reviewerName: 'Hala Gamal'),
        Review(comment: 'Good care, but long wait time.', stars: 4, reviewerName: 'Amr Mostafa'),
        Review(comment: 'Helped with my voice issues.', stars: 5, reviewerName: 'Rana Ahmed'),
        Review(comment: 'Very knowledgeable.', stars: 5, reviewerName: 'Sherif Mahmoud'),
        Review(comment: 'Clinic needs better scheduling.', stars: 4, reviewerName: 'Tarek Abdel Aziz'),
      ],
    ),
    Doctor(
      name: 'Dr. Amal Fathy',
      specialty: 'Gynecology',
      rating: 4.9,
      numberOfReviews: 1400,
      trait: 'Compassionate',
      location: 'Cairo: Maadi',
      fees: 200.0,
      waitingTimeMinutes: 45,
      availability: 'Sat, 26 Apr 02:00 PM',
      isSponsored: true,
      imageUrl: 'https://example.com/images/doctor_amal_fathy.jpg',
      bio: 'Dr. Amal Fathy is a compassionate gynecologist specializing in women’s health, prenatal care, and minimally invasive surgeries.',
      reviews: [
        Review(comment: 'Very compassionate, great care.', stars: 5, reviewerName: 'Mona Salah'),
        Review(comment: 'Good doctor, but clinic was busy.', stars: 4, reviewerName: 'Ali Hamed'),
        Review(comment: 'Professional and thorough.', stars: 5, reviewerName: 'Nourhan Mohamed'),
        Review(comment: 'Helped with my pregnancy, amazing.', stars: 5, reviewerName: 'Khaled Mostafa'),
        Review(comment: 'Slightly delayed, but excellent service.', stars: 4, reviewerName: 'Amal Fathy'),
      ],
    ),
    Doctor(
      name: 'Dr. Salma Youssef',
      specialty: 'Gynecology',
      rating: 4.8,
      numberOfReviews: 1100,
      trait: 'Skilled',
      location: 'Alexandria: Roushdy',
      fees: 190.0,
      waitingTimeMinutes: 40,
      availability: 'Sun, 27 Apr 03 кандидат: 00 PM',
      isSponsored: false,
      imageUrl: 'https://example.com/images/doctor_salma_youssef.jpg',
      bio: 'Dr. Salma Youssef provides expert gynecological care, focusing on fertility treatments and patient-centered reproductive health.',
      reviews: [
        Review(comment: 'Skilled and professional, great care.', stars: 5, reviewerName: 'Hala Gamal'),
        Review(comment: 'Good treatment, but long wait.', stars: 4, reviewerName: 'Amr Mostafa'),
        Review(comment: 'Helped with my fertility issues.', stars: 5, reviewerName: 'Rana Ahmed'),
        Review(comment: 'Very thorough and friendly.', stars: 5, reviewerName: 'Sherif Mahmoud'),
        Review(comment: 'Clinic needs better organization.', stars: 4, reviewerName: 'Tarek Abdel Aziz'),
      ],
    ),
    Doctor(
      name: 'Dr. Hoda Abdel Rahman',
      specialty: 'Gynecology',
      rating: 4.7,
      numberOfReviews: 950,
      trait: 'Friendly',
      location: 'Giza: Dokki',
      fees: 180.0,
      waitingTimeMinutes: 35,
      availability: 'Mon, 28 Apr 01:00 PM',
      isSponsored: false,
      imageUrl: 'https://example.com/images/doctor_hoda_abdelrahman.jpg',
      bio: 'Dr. Hoda Abdel Rahman is a friendly gynecologist with expertise in menopause management and adolescent gynecology.',
      reviews: [
        Review(comment: 'Very friendly, great experience.', stars: 5, reviewerName: 'Mona Salah'),
        Review(comment: 'Good care, but clinic was small.', stars: 4, reviewerName: 'Ali Hamed'),
        Review(comment: 'Professional and caring.', stars: 5, reviewerName: 'Nourhan Mohamed'),
        Review(comment: 'Helped with my condition.', stars: 5, reviewerName: 'Khaled Mostafa'),
        Review(comment: 'Average experience, long wait.', stars: 3, reviewerName: 'Amal Fathy'),
      ],
    ),
    Doctor(
      name: 'Dr. Mariam Khaled',
      specialty: 'Gynecology',
      rating: 4.9,
      numberOfReviews: 1300,
      trait: 'Professional',
      location: 'Tanta: El Geish St.',
      fees: 210.0,
      waitingTimeMinutes: 50,
      availability: 'Tue, 29 Apr 02:00 PM',
      isSponsored: true,
      imageUrl: 'https://example.com/images/doctor_mariam_khaled.jpg',
      bio: 'Dr. Mariam Khaled offers professional gynecological services, specializing in high-risk pregnancies and advanced diagnostic techniques.',
      reviews: [
        Review(comment: 'Professional and thorough, amazing care.', stars: 5, reviewerName: 'Hala Gamal'),
        Review(comment: 'Good service, but slightly expensive.', stars: 4, reviewerName: 'Amr Mostafa'),
        Review(comment: 'Very skilled, helped with my pregnancy.', stars: 5, reviewerName: 'Rana Ahmed'),
        Review(comment: 'Excellent doctor, highly recommend.', stars: 5, reviewerName: 'Sherif Mahmoud'),
        Review(comment: 'Clinic was crowded, but good care.', stars: 4, reviewerName: 'Tarek Abdel Aziz'),
      ],
    ),
    Doctor(
      name: 'Dr. Fatma Mostafa',
      specialty: 'Gynecology',
      rating: 4.6,
      numberOfReviews: 800,
      trait: 'Experienced',
      location: 'Cairo: Nasr City',
      fees: 200.0,
      waitingTimeMinutes: 45,
      availability: 'Wed, 30 Apr 04:00 PM',
      isSponsored: false,
      imageUrl: 'https://example.com/images/doctor_fatma_mostafa.jpg',
      bio: 'With 12 years of experience, Dr. Fatma Mostafa focuses on women’s wellness and preventive gynecological care.',
      reviews: [
        Review(comment: 'Experienced and professional.', stars: 5, reviewerName: 'Mona Salah'),
        Review(comment: 'Good care, but long wait time.', stars: 4, reviewerName: 'Ali Hamed'),
        Review(comment: 'Helped with my condition.', stars: 5, reviewerName: 'Nourhan Mohamed'),
        Review(comment: 'Very thorough and caring.', stars: 5, reviewerName: 'Khaled Mostafa'),
        Review(comment: 'Clinic needs better scheduling.', stars: 4, reviewerName: 'Amal Fathy'),
      ],
    ),
    Doctor(
      name: 'Dr. Mahmoud Samir',
      specialty: 'Internal Medicine',
      rating: 4.7,
      numberOfReviews: 900,
      trait: 'Patient',
      location: 'Cairo: Downtown',
      fees: 170.0,
      waitingTimeMinutes: 30,
      availability: 'Sat, 26 Apr 01:00 PM',
      isSponsored: false,
      imageUrl: 'https://example.com/images/doctor_mahmoud_samir.jpg',
      bio: 'Dr. Mahmoud Samir is a patient-focused internist specializing in chronic disease management and preventive care.',
      reviews: [
        Review(comment: 'Very patient and thorough.', stars: 5, reviewerName: 'Hala Gamal'),
        Review(comment: 'Good care, but clinic was busy.', stars: 4, reviewerName: 'Amr Mostafa'),
        Review(comment: 'Helped with my condition.', stars: 5, reviewerName: 'Rana Ahmed'),
        Review(comment: 'Friendly and professional.', stars: 5, reviewerName: 'Sherif Mahmoud'),
        Review(comment: 'Slightly delayed, but good service.', stars: 4, reviewerName: 'Tarek Abdel Aziz'),
      ],
    ),
    Doctor(
      name: 'Dr. Nourhan Ali',
      specialty: 'Internal Medicine',
      rating: 4.8,
      numberOfReviews: 1000,
      trait: 'Skilled',
      location: 'Alexandria: Sidi Gaber',
      fees: 180.0,
      waitingTimeMinutes: 35,
      availability: 'Sun, 27 Apr 02:00 PM',
      isSponsored: true,
      imageUrl: 'https://example.com/images/doctor_nourhan_ali.jpg',
      bio: 'Dr. Nourhan Ali excels in internal medicine, with a focus on diabetes management and comprehensive health assessments.',
      reviews: [
        Review(comment: 'Skilled and professional, great care.', stars: 5, reviewerName: 'Mona Salah'),
        Review(comment: 'Good doctor, but appointment was delayed.', stars: 4, reviewerName: 'Ali Hamed'),
        Review(comment: 'Very thorough, helped a lot.', stars: 5, reviewerName: 'Nourhan Mohamed'),
        Review(comment: 'Highly recommend, excellent care.', stars: 5, reviewerName: 'Khaled Mostafa'),
        Review(comment: 'Clinic needs better organization.', stars: 4, reviewerName: 'Amal Fathy'),
      ],
    ),
    Doctor(
      name: 'Dr. Ahmed Gamal',
      specialty: 'Internal Medicine',
      rating: 4.6,
      numberOfReviews: 750,
      trait: 'Friendly',
      location: 'Giza: Mohandessin',
      fees: 160.0,
      waitingTimeMinutes: 25,
      availability: 'Mon, 28 Apr 03:00 PM',
      isSponsored: false,
      imageUrl: 'https://example.com/images/doctor_ahmed_gamal.jpg',
      bio: 'Dr. Ahmed Gamal is a friendly internist specializing in gastrointestinal disorders and patient education.',
      reviews: [
        Review(comment: 'Very friendly, great experience.', stars: 5, reviewerName: 'Hala Gamal'),
        Review(comment: 'Good care, but clinic was small.', stars: 4, reviewerName: 'Amr Mostafa'),
        Review(comment: 'Professional and caring.', stars: 5, reviewerName: 'Rana Ahmed'),
        Review(comment: 'Helped with my condition.', stars: 5, reviewerName: 'Sherif Mahmoud'),
        Review(comment: 'Average experience, long wait.', stars: 3, reviewerName: 'Tarek Abdel Aziz'),
      ],
    ),
    Doctor(
      name: 'Dr. Sara Mohamed',
      specialty: 'Internal Medicine',
      rating: 4.9,
      numberOfReviews: 1200,
      trait: 'Professional',
      location: 'Tanta: El Nady St.',
      fees: 190.0,
      waitingTimeMinutes: 40,
      availability: 'Tue, 29 Apr 01:00 PM',
      isSponsored: true,
      imageUrl: 'https://example.com/images/doctor_sara_mohamed.jpg',
      bio: 'Dr. Sara Mohamed provides professional internal medicine care, with expertise in hypertension and metabolic disorders.',
      reviews: [
        Review(comment: 'Professional and thorough, amazing care.', stars: 5, reviewerName: 'Mona Salah'),
        Review(comment: 'Good service, but slightly expensive.', stars: 4, reviewerName: 'Ali Hamed'),
        Review(comment: 'Very skilled, helped with my condition.', stars: 5, reviewerName: 'Nourhan Mohamed'),
        Review(comment: 'Excellent doctor, highly recommend.', stars: 5, reviewerName: 'Khaled Mostafa'),
        Review(comment: 'Clinic was crowded, but good care.', stars: 4, reviewerName: 'Amal Fathy'),
      ],
    ),
    Doctor(
      name: 'Dr. Khaled Abdel Aziz',
      specialty: 'Internal Medicine',
      rating: 4.5,
      numberOfReviews: 600,
      trait: 'Experienced',
      location: 'Cairo: Zamalek',
      fees: 200.0,
      waitingTimeMinutes: 45,
      availability: 'Wed, 30 Apr 02:00 PM',
      isSponsored: false,
      imageUrl: 'https://example.com/images/doctor_khaled_abdelaziz.jpg',
      bio: 'With over 10 years in internal medicine, Dr. Khaled specializes in autoimmune diseases and holistic care.',
      reviews: [
        Review(comment: 'Experienced and professional.', stars: 5, reviewerName: 'Hala Gamal'),
        Review(comment: 'Good care, but long wait time.', stars: 4, reviewerName: 'Amr Mostafa'),
        Review(comment: 'Helped with my condition.', stars: 5, reviewerName: 'Rana Ahmed'),
        Review(comment: 'Very thorough and caring.', stars: 5, reviewerName: 'Sherif Mahmoud'),
        Review(comment: 'Clinic needs better scheduling.', stars: 4, reviewerName: 'Tarek Abdel Aziz'),
      ],
    ),
    Doctor(
      name: 'Dr. Omar Mostafa',
      specialty: 'Neurology',
      rating: 4.8,
      numberOfReviews: 1100,
      trait: 'Skilled',
      location: 'Cairo: Maadi',
      fees: 220.0,
      waitingTimeMinutes: 50,
      availability: 'Sat, 26 Apr 03:00 PM',
      isSponsored: true,
      imageUrl: 'https://example.com/images/doctor_omar_mostafa.jpg',
      bio: 'Dr. Omar Mostafa is a skilled neurologist specializing in epilepsy and stroke management with advanced diagnostic techniques.',
      reviews: [
        Review(comment: 'Skilled and professional, great care.', stars: 5, reviewerName: 'Mona Salah'),
        Review(comment: 'Good doctor, but appointment was delayed.', stars: 4, reviewerName: 'Ali Hamed'),
        Review(comment: 'Very thorough, helped a lot.', stars: 5, reviewerName: 'Nourhan Mohamed'),
        Review(comment: 'Highly recommend, excellent care.', stars: 5, reviewerName: 'Khaled Mostafa'),
        Review(comment: 'Clinic needs better organization.', stars: 4, reviewerName: 'Amal Fathy'),
      ],
    ),
    Doctor(
      name: 'Dr. Hala Mahmoud',
      specialty: 'Neurology',
      rating: 4.7,
      numberOfReviews: 900,
      trait: 'Patient',
      location: 'Alexandria: Smouha',
      fees: 200.0,
      waitingTimeMinutes: 45,
      availability: 'Sun, 27 Apr 04:00 PM',
      isSponsored: false,
      imageUrl: 'https://example.com/images/doctor_hala_mahmoud.jpg',
      bio: 'Dr. Hala Mahmoud provides patient-focused neurological care, with expertise in migraine treatment and neurorehabilitation.',
      reviews: [
        Review(comment: 'Very patient and thorough.', stars: 5, reviewerName: 'Hala Gamal'),
        Review(comment: 'Good care, but clinic was busy.', stars: 4, reviewerName: 'Amr Mostafa'),
        Review(comment: 'Helped with my migraines.', stars: 5, reviewerName: 'Rana Ahmed'),
        Review(comment: 'Friendly and professional.', stars: 5, reviewerName: 'Sherif Mahmoud'),
        Review(comment: 'Slightly delayed, but good service.', stars: 4, reviewerName: 'Tarek Abdel Aziz'),
      ],
    ),
    Doctor(
      name: 'Dr. Ali Abdel Rahman',
      specialty: 'Neurology',
      rating: 4.6,
      numberOfReviews: 800,
      trait: 'Friendly',
      location: 'Giza: Dokki',
      fees: 190.0,
      waitingTimeMinutes: 40,
      availability: 'Mon, 28 Apr 02:00 PM',
      isSponsored: false,
      imageUrl: 'https://example.com/images/doctor_ali_abdelrahman.jpg',
      bio: 'Dr. Ali Abdel Rahman is a friendly neurologist specializing in Parkinson’s disease and patient-centered care.',
      reviews: [
        Review(comment: 'Very friendly, great experience.', stars: 5, reviewerName: 'Mona Salah'),
        Review(comment: 'Good care, but clinic was small.', stars: 4, reviewerName: 'Ali Hamed'),
        Review(comment: 'Professional and caring.', stars: 5, reviewerName: 'Nourhan Mohamed'),
        Review(comment: 'Helped with my condition.', stars: 5, reviewerName: 'Khaled Mostafa'),
        Review(comment: 'Average experience, long wait.', stars: 3, reviewerName: 'Amal Fathy'),
      ],
    ),
    Doctor(
      name: 'Dr. Nourhan Khaled',
      specialty: 'Neurology',
      rating: 4.9,
      numberOfReviews: 1300,
      trait: 'Professional',
      location: 'Tanta: El Geish St.',
      fees: 230.0,
      waitingTimeMinutes: 55,
      availability: 'Tue, 29 Apr 01:00 PM',
      isSponsored: true,
      imageUrl: 'https://example.com/images/doctor_nourhan_khaled.jpg',
      bio: 'Dr. Nourhan Khaled offers professional neurological care, with a focus on multiple sclerosis and advanced neuroimaging.',
      reviews: [
        Review(comment: 'Professional and thorough, amazing care.', stars: 5, reviewerName: 'Hala Gamal'),
        Review(comment: 'Good service, but slightly expensive.', stars: 4, reviewerName: 'Amr Mostafa'),
        Review(comment: 'Very skilled, helped with my condition.', stars: 5, reviewerName: 'Rana Ahmed'),
        Review(comment: 'Excellent doctor, highly recommend.', stars: 5, reviewerName: 'Sherif Mahmoud'),
        Review(comment: 'Clinic was crowded, but good care.', stars: 4, reviewerName: 'Tarek Abdel Aziz'),
      ],
    ),
    Doctor(
      name: 'Dr. Ahmed Fathy',
      specialty: 'Neurology',
      rating: 4.5,
      numberOfReviews: 700,
      trait: 'Experienced',
      location: 'Cairo: Nasr City',
      fees: 210.0,
      waitingTimeMinutes: 50,
      availability: 'Wed, 30 Apr 03:00 PM',
      isSponsored: false,
      imageUrl: 'https://example.com/images/doctor_ahmed_fathy.jpg',
      bio: 'With 12 years of experience, Dr. Ahmed Fathy specializes in neuropathy and comprehensive neurological assessments.',
      reviews: [
        Review(comment: 'Experienced and professional.', stars: 5, reviewerName: 'Mona Salah'),
        Review(comment: 'Good care, but long wait time.', stars: 4, reviewerName: 'Ali Hamed'),
        Review(comment: 'Helped with my condition.', stars: 5, reviewerName: 'Nourhan Mohamed'),
        Review(comment: 'Very thorough and caring.', stars: 5, reviewerName: 'Khaled Mostafa'),
        Review(comment: 'Clinic needs better scheduling.', stars: 4, reviewerName: 'Amal Fathy'),
      ],
    ),
    Doctor(
      name: 'Dr. Mohamed Abdel Aziz',
      specialty: 'Orthopedics',
      rating: 4.8,
      numberOfReviews: 1000,
      trait: 'Skilled',
      location: 'Cairo: Heliopolis',
      fees: 200.0,
      waitingTimeMinutes: 40,
      availability: 'Sat, 26 Apr 02:00 PM',
      isSponsored: true,
      imageUrl: 'https://example.com/images/doctor_mohamed_abdelaziz.jpg',
      bio: 'Dr. Mohamed Abdel Aziz is a skilled orthopedic surgeon specializing in joint replacement and sports injuries.',
      reviews: [
        Review(comment: 'Skilled and professional, great care.', stars: 5, reviewerName: 'Mona Salah'),
        Review(comment: 'Good doctor, but appointment was delayed.', stars: 4, reviewerName: 'Ali Hamed'),
        Review(comment: 'Very thorough, helped a lot.', stars: 5, reviewerName: 'Nourhan Mohamed'),
        Review(comment: 'Highly recommend, excellent care.', stars: 5, reviewerName: 'Khaled Mostafa'),
        Review(comment: 'Clinic needs better organization.', stars: 4, reviewerName: 'Amal Fathy'),
      ],
    ),
    Doctor(
      name: 'Dr. Aya Gamal',
      specialty: 'Orthopedics',
      rating: 4.7,
      numberOfReviews: 900,
      trait: 'Patient',
      location: 'Alexandria: Roushdy',
      fees: 190.0,
      waitingTimeMinutes: 35,
      availability: 'Sun, 27 Apr 03:00 PM',
      isSponsored: false,
      imageUrl: 'https://example.com/images/doctor_aya_gamal.jpg',
      bio: 'Dr. Aya Gamal provides patient-focused orthopedic care, with expertise in fracture management and rehabilitation.',
      reviews: [
        Review(comment: 'Very patient and thorough.', stars: 5, reviewerName: 'Hala Gamal'),
        Review(comment: 'Good care, but clinic was busy.', stars: 4, reviewerName: 'Amr Mostafa'),
        Review(comment: 'Helped with my fracture.', stars: 5, reviewerName: 'Rana Ahmed'),
        Review(comment: 'Friendly and professional.', stars: 5, reviewerName: 'Sherif Mahmoud'),
        Review(comment: 'Slightly delayed, but good service.', stars: 4, reviewerName: 'Tarek Abdel Aziz'),
      ],
    ),
    Doctor(
      name: 'Dr. Khaled Mahmoud',
      specialty: 'Orthopedics',
      rating: 4.6,
      numberOfReviews: 800,
      trait: 'Friendly',
      location: 'Giza: Faisal',
      fees: 180.0,
      waitingTimeMinutes: 30,
      availability: 'Mon, 28 Apr 01:00 PM',
      isSponsored: false,
      imageUrl: 'https://example.com/images/doctor_khaled_mahmoud.jpg',
      bio: 'Dr. Khaled Mahmoud is a friendly orthopedist specializing in spine disorders and minimally invasive surgeries.',
      reviews: [
        Review(comment: 'Very friendly, great experience.', stars: 5, reviewerName: 'Mona Salah'),
        Review(comment: 'Good care, but clinic was small.', stars: 4, reviewerName: 'Ali Hamed'),
        Review(comment: 'Professional and caring.', stars: 5, reviewerName: 'Nourhan Mohamed'),
        Review(comment: 'Helped with my condition.', stars: 5, reviewerName: 'Khaled Mostafa'),
        Review(comment: 'Average experience, long wait.', stars: 3, reviewerName: 'Amal Fathy'),
      ],
    ),
    Doctor(
      name: 'Dr. Sara Mostafa',
      specialty: 'Orthopedics',
      rating: 4.9,
      numberOfReviews: 1200,
      trait: 'Professional',
      location: 'Tanta: El Nady St.',
      fees: 210.0,
      waitingTimeMinutes: 45,
      availability: 'Tue, 29 Apr 02:00 PM',
      isSponsored: true,
      imageUrl: 'https://example.com/images/doctor_sara_mostafa.jpg',
      bio: 'Dr. Sara Mostafa offers professional orthopedic care, with a focus on pediatric orthopedics and trauma care.',
      reviews: [
        Review(comment: 'Professional and thorough, amazing care.', stars: 5, reviewerName: 'Hala Gamal'),
        Review(comment: 'Good service, but slightly expensive.', stars: 4, reviewerName: 'Amr Mostafa'),
        Review(comment: 'Very skilled, helped with my condition.', stars: 5, reviewerName: 'Rana Ahmed'),
        Review(comment: 'Excellent doctor, highly recommend.', stars: 5, reviewerName: 'Sherif Mahmoud'),
        Review(comment: 'Clinic was crowded, but good care.', stars: 4, reviewerName: 'Tarek Abdel Aziz'),
      ],
    ),
    Doctor(
      name: 'Dr. Ahmed Hamed',
      specialty: 'Orthopedics',
      rating: 4.5,
      numberOfReviews: 700,
      trait: 'Experienced',
      location: 'Cairo: Zamalek',
      fees: 220.0,
      waitingTimeMinutes: 50,
      availability: 'Wed, 30 Apr 04:00 PM',
      isSponsored: false,
      imageUrl: 'https://example.com/images/doctor_ahmed_hamed.jpg',
      bio: 'With 10 years of experience, Dr. Ahmed Hamed specializes in arthroscopic surgeries and orthopedic rehabilitation.',
      reviews: [
        Review(comment: 'Experienced and professional.', stars: 5, reviewerName: 'Mona Salah'),
        Review(comment: 'Good care, but long wait time.', stars: 4, reviewerName: 'Ali Hamed'),
        Review(comment: 'Helped with my condition.', stars: 5, reviewerName: 'Nourhan Mohamed'),
        Review(comment: 'Very thorough and caring.', stars: 5, reviewerName: 'Khaled Mostafa'),
        Review(comment: 'Clinic needs better scheduling.', stars: 4, reviewerName: 'Amal Fathy'),
      ],
    ),
    Doctor(
      name: 'Dr. Fatima Ali',
      specialty: 'Pediatrics',
      rating: 4.9,
      numberOfReviews: 1300,
      trait: 'Compassionate',
      location: 'Cairo: Maadi',
      fees: 180.0,
      waitingTimeMinutes: 35,
      availability: 'Sat, 26 Apr 01:00 PM',
      isSponsored: true,
      imageUrl: 'https://example.com/images/doctor_fatima_ali.jpg',
      bio: 'Dr. Fatima Ali is a compassionate pediatrician specializing in child development and preventive care for infants and children.',
      reviews: [
        Review(comment: 'Very compassionate, great with kids.', stars: 5, reviewerName: 'Hala Gamal'),
        Review(comment: 'Good care, but clinic was busy.', stars: 4, reviewerName: 'Amr Mostafa'),
        Review(comment: 'Professional and thorough.', stars: 5, reviewerName: 'Rana Ahmed'),
        Review(comment: 'Amazing doctor, highly recommend.', stars: 5, reviewerName: 'Sherif Mahmoud'),
        Review(comment: 'Slightly delayed, but excellent service.', stars: 4, reviewerName: 'Tarek Abdel Aziz'),
      ],
    ),
    Doctor(
      name: 'Dr. Nourhan Gamal',
      specialty: 'Pediatrics',
      rating: 4.8,
      numberOfReviews: 1100,
      trait: 'Skilled',
      location: 'Alexandria: Sidi Gaber',
      fees: 170.0,
      waitingTimeMinutes: 30,
      availability: 'Sun, 27 Apr 02:00 PM',
      isSponsored: false,
      imageUrl: 'https://example.com/images/doctor_nourhan_gamal.jpg',
      bio: 'Dr. Nourhan Gamal excels in pediatric care, with a focus on infectious diseases and vaccination programs.',
      reviews: [
        Review(comment: 'Skilled and professional, great care.', stars: 5, reviewerName: 'Mona Salah'),
        Review(comment: 'Good doctor, but appointment was delayed.', stars: 4, reviewerName: 'Ali Hamed'),
        Review(comment: 'Very thorough, helped a lot.', stars: 5, reviewerName: 'Nourhan Mohamed'),
        Review(comment: 'Highly recommend, excellent care.', stars: 5, reviewerName: 'Khaled Mostafa'),
        Review(comment: 'Clinic needs better organization.', stars: 4, reviewerName: 'Amal Fathy'),
      ],
    ),
    Doctor(
      name: 'Dr. Mohamed Abdel Rahman',
      specialty: 'Pediatrics',
      rating: 4.7,
      numberOfReviews: 950,
      trait: 'Friendly',
      location: 'Giza: Mohandessin',
      fees: 160.0,
      waitingTimeMinutes: 25,
      availability: 'Mon, 28 Apr 03:00 PM',
      isSponsored: false,
      imageUrl: 'https://example.com/images/doctor_mohamed_abdelrahman.jpg',
      bio: 'Dr. Mohamed Abdel Rahman is a friendly pediatrician specializing in neonatal care and parent education.',
      reviews: [
        Review(comment: 'Very friendly, great experience.', stars: 5, reviewerName: 'Hala Gamal'),
        Review(comment: 'Good care, but clinic was small.', stars: 4, reviewerName: 'Amr Mostafa'),
        Review(comment: 'Professional and caring.', stars: 5, reviewerName: 'Rana Ahmed'),
        Review(comment: 'Helped with my condition.', stars: 5, reviewerName: 'Sherif Mahmoud'),
        Review(comment: 'Average experience, long wait.', stars: 3, reviewerName: 'Tarek Abdel Aziz'),
      ],
    ),
    Doctor(
      name: 'Dr. Aya Khaled',
      specialty: 'Pediatrics',
      rating: 4.9,
      numberOfReviews: 1200,
      trait: 'Professional',
      location: 'Tanta: El Geish St.',
      fees: 190.0,
      waitingTimeMinutes: 40,
      availability: 'Tue, 29 Apr 01:00 PM',
      isSponsored: true,
      imageUrl: 'https://example.com/images/doctor_aya_khaled.jpg',
      bio: 'Dr. Aya Khaled provides professional pediatric care, with expertise in pediatric allergies and asthma management.',
      reviews: [
        Review(comment: 'Professional and thorough, amazing care.', stars: 5, reviewerName: 'Mona Salah'),
        Review(comment: 'Good service, but slightly expensive.', stars: 4, reviewerName: 'Ali Hamed'),
        Review(comment: 'Very skilled, helped with my condition.', stars: 5, reviewerName: 'Nourhan Mohamed'),
        Review(comment: 'Excellent doctor, highly recommend.', stars: 5, reviewerName: 'Khaled Mostafa'),
        Review(comment: 'Clinic was crowded, but good care.', stars: 4, reviewerName: 'Amal Fathy'),
      ],
    ),
    Doctor(
      name: 'Dr. Ahmed Mostafa',
      specialty: 'Pediatrics',
      rating: 4.6,
      numberOfReviews: 800,
      trait: 'Experienced',
      location: 'Cairo: Nasr City',
      fees: 200.0,
      waitingTimeMinutes: 45,
      availability: 'Wed, 30 Apr 02:00 PM',
      isSponsored: false,
      imageUrl: 'https://example.com/images/doctor_ahmed_mostafa.jpg',
      bio: 'With 12 years of experience, Dr. Ahmed Mostafa specializes in pediatric nutrition and growth disorders.',
      reviews: [
        Review(comment: 'Experienced and professional.', stars: 5, reviewerName: 'Hala Gamal'),
        Review(comment: 'Good care, but long wait time.', stars: 4, reviewerName: 'Amr Mostafa'),
        Review(comment: 'Helped with my condition.', stars: 5, reviewerName: 'Rana Ahmed'),
        Review(comment: 'Very thorough and caring.', stars: 5, reviewerName: 'Sherif Mahmoud'),
        Review(comment: 'Clinic needs better scheduling.', stars: 4, reviewerName: 'Tarek Abdel Aziz'),
      ],
    ),
    Doctor(
      name: 'Dr. Hala Fathy',
      specialty: 'Psychiatry',
      rating: 4.8,
      numberOfReviews: 1000,
      trait: 'Empathetic',
      location: 'Cairo: Heliopolis',
      fees: 220.0,
      waitingTimeMinutes: 50,
      availability: 'Sat, 26 Apr 03:00 PM',
      isSponsored: true,
      imageUrl: 'https://example.com/images/doctor_hala_fathy.jpg',
      bio: 'Dr. Hala Fathy is an empathetic psychiatrist specializing in anxiety disorders and cognitive behavioral therapy.',
      reviews: [
        Review(comment: 'Very empathetic, great care.', stars: 5, reviewerName: 'Mona Salah'),
        Review(comment: 'Good doctor, but clinic was busy.', stars: 4, reviewerName: 'Ali Hamed'),
        Review(comment: 'Professional and thorough.', stars: 5, reviewerName: 'Nourhan Mohamed'),
        Review(comment: 'Helped with my anxiety, amazing.', stars: 5, reviewerName: 'Khaled Mostafa'),
        Review(comment: 'Slightly delayed, but excellent service.', stars: 4, reviewerName: 'Amal Fathy'),
      ],
    ),
    Doctor(
      name: 'Dr. Nourhan Mahmoud',
      specialty: 'Psychiatry',
      rating: 4.7,
      numberOfReviews: 900,
      trait: 'Patient',
      location: 'Alexandria: Smouha',
      fees: 200.0,
      waitingTimeMinutes: 45,
      availability: 'Sun, 27 Apr 04:00 PM',
      isSponsored: false,
      imageUrl: 'https://example.com/images/doctor_nourhan_mahmoud.jpg',
      bio: 'Dr. Nourhan Mahmoud provides patient-focused psychiatric care, with expertise in depression and stress management.',
      reviews: [
        Review(comment: 'Very patient and thorough.', stars: 5, reviewerName: 'Hala Gamal'),
        Review(comment: 'Good care, but clinic was small.', stars: 4, reviewerName: 'Amr Mostafa'),
        Review(comment: 'Helped with my depression.', stars: 5, reviewerName: 'Rana Ahmed'),
        Review(comment: 'Friendly and professional.', stars: 5, reviewerName: 'Sherif Mahmoud'),
        Review(comment: 'Average experience, long wait.', stars: 3, reviewerName: 'Tarek Abdel Aziz'),
      ],
    ),
    Doctor(
      name: 'Dr. Ali Gamal',
      specialty: 'Psychiatry',
      rating: 4.6,
      numberOfReviews: 800,
      trait: 'Friendly',
      location: 'Giza: Dokki',
      fees: 190.0,
      waitingTimeMinutes: 40,
      availability: 'Mon, 28 Apr 02:00 PM',
      isSponsored: false,
      imageUrl: 'https://example.com/images/doctor_ali_gamal.jpg',
      bio: 'Dr. Ali Gamal is a friendly psychiatrist specializing in addiction treatment and mental health counseling.',
      reviews: [
        Review(comment: 'Very friendly, great experience.', stars: 5, reviewerName: 'Mona Salah'),
        Review(comment: 'Good care, but clinic was busy.', stars: 4, reviewerName: 'Ali Hamed'),
        Review(comment: 'Professional and caring.', stars: 5, reviewerName: 'Nourhan Mohamed'),
        Review(comment: 'Helped with my condition.', stars: 5, reviewerName: 'Khaled Mostafa'),
        Review(comment: 'Clinic needs better organization.', stars: 4, reviewerName: 'Amal Fathy'),
      ],
    ),
    Doctor(
      name: 'Dr. Sara Abdel Aziz',
      specialty: 'Psychiatry',
      rating: 4.9,
      numberOfReviews: 1200,
      trait: 'Professional',
      location: 'Tanta: El Nady St.',
      fees: 230.0,
      waitingTimeMinutes: 55,
      availability: 'Tue, 29 Apr 01:00 PM',
      isSponsored: true,
      imageUrl: 'https://example.com/images/doctor_sara_abdelaziz.jpg',
      bio: 'Dr. Sara Abdel Aziz offers professional psychiatric care, with a focus on mood disorders and psychotherapy.',
      reviews: [
        Review(comment: 'Professional and thorough, amazing care.', stars: 5, reviewerName: 'Hala Gamal'),
        Review(comment: 'Good service, but slightly expensive.', stars: 4, reviewerName: 'Amr Mostafa'),
        Review(comment: 'Very skilled, helped with my condition.', stars: 5, reviewerName: 'Rana Ahmed'),
        Review(comment: 'Excellent doctor, highly recommend.', stars: 5, reviewerName: 'Sherif Mahmoud'),
        Review(comment: 'Clinic was crowded, but good care.', stars: 4, reviewerName: 'Tarek Abdel Aziz'),
      ],
    ),
    Doctor(
      name: 'Dr. Ahmed Khaled',
      specialty: 'Psychiatry',
      rating: 4.5,
      numberOfReviews: 700,
      trait: 'Experienced',
      location: 'Cairo: Zamalek',
      fees: 210.0,
      waitingTimeMinutes: 50,
      availability: 'Wed, 30 Apr 03:00 PM',
      isSponsored: false,
      imageUrl: 'https://example.com/images/doctor_ahmed_khaled_psych.jpg',
      bio: 'With 10 years of experience, Dr. Ahmed Khaled specializes in child psychiatry and behavioral therapy.',
      reviews: [
        Review(comment: 'Experienced and professional.', stars: 5, reviewerName: 'Mona Salah'),
        Review(comment: 'Good care, but long wait time.', stars: 4, reviewerName: 'Ali Hamed'),
        Review(comment: 'Helped with my condition.', stars: 5, reviewerName: 'Nourhan Mohamed'),
        Review(comment: 'Very thorough and caring.', stars: 5, reviewerName: 'Khaled Mostafa'),
        Review(comment: 'Clinic needs better scheduling.', stars: 4, reviewerName: 'Amal Fathy'),
      ],
    ),
  ];

  DoctorsData({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Doctors Data Storage'),
        backgroundColor: Colors.blue,
      ),
      body: const Center(
        child: Text(
          'This page stores the data of 50 doctors with image URLs and reviews.\nAccess the data via DoctorsData.doctors list.',
          textAlign: TextAlign.center,
          style: TextStyle(fontSize: 16),
        ),
      ),
    );
  }
}
