// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDahf-1AnGw5lrsrv6iyiuvUu7OJv91V1A',
    appId: '1:646727714071:web:951e97e5c942fd4e512352',
    messagingSenderId: '646727714071',
    projectId: 'medics-app-2025-xyz',
    authDomain: 'medics-app-2025-xyz.firebaseapp.com',
    storageBucket: 'medics-app-2025-xyz.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMf_yjsdWp5TM94Tdhn4WPlq2wXO5VJfE',
    appId: '1:646727714071:android:9a4700927b7831f7512352',
    messagingSenderId: '646727714071',
    projectId: 'medics-app-2025-xyz',
    storageBucket: 'medics-app-2025-xyz.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR4jSm6xovN8HFvTHHFwxVG3BnYfOQKeY',
    appId: '1:646727714071:ios:db94ce7c4cddd9d4512352',
    messagingSenderId: '646727714071',
    projectId: 'medics-app-2025-xyz',
    storageBucket: 'medics-app-2025-xyz.firebasestorage.app',
    iosBundleId: 'com.example.medics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAR4jSm6xovN8HFvTHHFwxVG3BnYfOQKeY',
    appId: '1:646727714071:ios:db94ce7c4cddd9d4512352',
    messagingSenderId: '646727714071',
    projectId: 'medics-app-2025-xyz',
    storageBucket: 'medics-app-2025-xyz.firebasestorage.app',
    iosBundleId: 'com.example.medics',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDahf-1AnGw5lrsrv6iyiuvUu7OJv91V1A',
    appId: '1:646727714071:web:0a88221ef3477cbf512352',
    messagingSenderId: '646727714071',
    projectId: 'medics-app-2025-xyz',
    authDomain: 'medics-app-2025-xyz.firebaseapp.com',
    storageBucket: 'medics-app-2025-xyz.firebasestorage.app',
  );
}
